name: "Network settings"
stages:
  initramfs:
  # Setup network
  - name: "Network setup"
    files:
    - path: /etc/sysconfig/network/ifcfg-eth0
      content: |
        BOOTPROTO='dhcp'
        STARTMODE='onboot'
      permissions: 0600
      owner: 0
      group: 0
